### ISSUE TITLE
'Client' object has no attribute 'run_sync_query'

### ISSUE THREAD

**Issue by aaronduino** [ofek/pypinfo#27]
First of all, thank you so much for building this package.
I'm excited to start using it, but it has been crashing for me on every query run:

```
coding@Aarons-MBP pypinfo (master)$ pypinfo django date
Traceback (most recent call last):
  File "/usr/local/bin/pypinfo", line 11, in <module>
    load_entry_point('pypinfo==5.0.0', 'console_scripts', 'pypinfo')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pypinfo/cli.py", line 89, in pypinfo
    query = client.run_sync_query(built_query)
AttributeError: 'Client' object has no attribute 'run_sync_query'
```

I tried python2, updating gcloud, etc. to no avail.

**Comment by aaronduino** [comment]
Thanks

**Comment by ofek** [comment]
This is fixed in `6.0.0`, thank you! Google released a new version of their BigQuery lib.

**Comment by aishgrt1** [comment]
I am using it using Ananconda, but still shows the same error for me. I have the updated version of the Google Big Query:

AttributeError: 'Client' object has no attribute 'run_sync_query'

**Comment by ofek** [comment]
@aishgrt1 Can you please show me the output of `pip freeze`?

**Comment by aishgrt1** [comment]
These are the google related packages are:
google-api-core           0.1.1                    py36_1    conda-forge
google-api-python-client  1.6.4                      py_0    conda-forge
google-auth               1.2.1                      py_0    conda-forge
google-cloud-bigquery     0.29.0                     py_0    conda-forge
google-cloud-core         0.28.0                     py_0    conda-forge
google-resumable-media    0.3.1                      py_0    conda-forge
googleapis-common-protos  1.5.3                    py36_0    conda-forge

**Comment by ofek** [comment]
I need to see the version of pypinfo.

**Comment by aishgrt1** [comment]
There is no package called pypinfo

**Comment by aishgrt1** [comment]
>>> print(pypinfo.__version__)
8.0.0

**Comment by ofek** [comment]
Do `pypinfo --version`

**Comment by aishgrt1** [comment]
it's 8.0.0

**Comment by aishgrt1** [comment]
>>> from google.cloud import bigquery
>>> client = bigquery.Client()
>>dir(client)
['SCOPE', '_SET_PROJECT', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_call_api', '_connection', '_credentials', '_determine_default', '_do_multipart_upload', '_do_resumable_upload', '_get_query_results', '_http', '_http_internal', '_initiate_resumable_upload', 'cancel_job', 'copy_table', 'create_dataset', 'create_rows', 'create_rows_json', 'create_table', 'dataset', 'delete_dataset', 'delete_table', 'extract_table', 'from_service_account_json', 'get_dataset', 'get_job', 'get_table', 'insert_rows', 'insert_rows_json', 'job_from_resource', 'list_dataset_tables', 'list_datasets', 'list_jobs', 'list_partitions', 'list_projects', 'list_rows', 'list_tables', 'load_table_from_file', 'load_table_from_uri', 'project', 'query', 'update_dataset', 'update_table']


So the version of google-cloud-bigquery is 0.29.0 , and the list of functions, doesn't contain run_sync_query

**Comment by aishgrt1** [comment]
the "run_sync_query" has been changed to "query" in 0.29.0 version

**Comment by ofek** [comment]
The error implies pypinfo<6.0.0 but I don't know how that is possible.

**Comment by ofek** [comment]
Try re-installing pypinfo.
